export const defaultDimensionData = [
  {
    definition: "Default definition 1",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 2",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 3",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 4",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 5",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 6",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 7",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 8",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 9",
    type: "Practice",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 10",
    type: "Beliefs",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 11",
    type: "Beliefs",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 12",
    type: "Beliefs",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 13",
    type: "Beliefs",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
  {
    definition: "Default definition 14",
    type: "Beliefs",
    leftCardStatement: "left definition",
    rightCardStatement: "right definition",
    leftCardDefaultSliderPosition: 0,
    rightCardDefaultSliderPosition: 100,
    marks: [
      { position: 0, label: "Left Mark" },
      { position: 100, label: "Right Mark" },
    ],
  },
];
